### ISSUE TITLE
setup.sh: requires calling with root permissions

### ISSUE THREAD

**Issue by vvanpo** [avanpo/.env#2]
The readme currently says to call setup.sh with `sudo`, meaning all the directories are created in `/root` directory, not the user's home directory. I realize `sudo` is needed for the last step, but why are you installing your local scripts into the global install directory anyway? Better to just add `~/.env/bin/` into your `PATH`.

**Comment by avanpo** [comment]
Oops, you're right. I've never actually used `setup.sh`, I was just tracking what I've been doing (although I failed at that, since I've forgotten all the packages I've installed).

I'll fix it.
